server {
    listen 3000;
    
    # 1. Serve the React App
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Secretly forward /api/ requests to the Python backend!
    location /api/ {
        proxy_pass http://localhost:8000/; 
    }
}