server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://api-backend-svc:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Reverse Proxy for Facebook to strip X-Frame-Options and fix relative paths
    location /fb-proxy/ {
        proxy_pass https://www.facebook.com/;
        proxy_ssl_server_name on;
        proxy_set_header Host www.facebook.com;
        proxy_set_header Referer "https://www.facebook.com/";
        proxy_set_header User-Agent $http_user_agent;
        
        # Force Facebook to return uncompressed HTML so Nginx can modify it
        proxy_set_header Accept-Encoding "";
        
        # Strip restrictive headers
        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
        proxy_hide_header Content-Security-Policy-Report-Only;
        proxy_hide_header X-Content-Type-Options;
        
        # Inject <base> tag to fix requireLazy broken relative script paths!
        sub_filter '<head>' '<head><base href="https://www.facebook.com/" />';
        sub_filter_once on;
        
        proxy_buffering off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
